### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by danimalweb** [evil-shrike/ddns-updater#1]
This looks great, thanks for putting it together. I have a couple of questions about the script.

In order to update the DNS records in Namecheap are the login details being sent to a 3rd party or directly to Namecheap servers?

I'm a little worried about having my Namecheap password inside a script as the account holds a lot of critical domains. I could move it to a new Namecheap account.

Do you think that this script is easily updatable to use the Namecheap API service?

**Comment by evil-shrike** [comment]
Hi @danimalweb! I believe `park-your-domain.com` is a namecheap's service, I took it from their documentation - see  https://www.namecheap.com/support/knowledgebase/article.aspx/583/11/how-do-i-configure-ddclient
Whois - https://www.whois.com/whois/park-your-domain.com

**Comment by danimalweb** [comment]
Gotcha thanks, so it uses ddclient.
