### ISSUE TITLE
failed to update

### ISSUE THREAD

**Issue by jeremy-windsor** [evil-shrike/ddns-updater#2]
i installed node.js 4.0 and got everything installed however i'm getting the following error:

[/share/CACHEDEV1_DATA/lib/ddns] # node app.js
Started.
[16/03 07:00:30] Checking. Next check in 2 hours
External IP resolved via ipify : 68.x.x.x
IP changed from undefined to 68.x.x.x
Failed to update IP via namecheap:
[Error: [object Object]]
Failed to update IP via namecheap:
[Error: [object Object]]
^C

**Comment by evil-shrike** [comment]
Sorry to hear that.
In your app.js there should be  line like:
```
updater.on('update:error', function (err, domain) {
	console.log('Failed to update IP via ' + domain.service + ':');
	console.log(err);
});
```
In your case it seems the error (`err`) is an object.  So change to:
```
	console.log(JSON.stringify(err));
```
and you'll see the error from Namecheap.
Probably you have incorrect settins.password in `config.json`...

**Comment by jeremy-windsor** [comment]
you're right, it was a config.json error.  can you tell me which node version i should install in qnap? i have all 3 available installed currently.  thanks!
